// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package board

import (
	"codetest/board/controller"
	"codetest/board/repository"
	"codetest/board/service"
)

// Injectors from wire.go:

func InitializeBoardController() controller.Controller {
	boardRepository := repository.NewRepository()
	boardService := service.NewService(boardRepository)
	controllerController := controller.NewController(boardService)
	return controllerController
}

func InitializeReplyController() controller.ReplyController {
	replyRepository := repository.NewReplyRepository()
	boardRepository := repository.NewRepository()
	replyService := service.NewReplyService(replyRepository, boardRepository)
	replyController := controller.NewReplyController(replyService)
	return replyController
}
