version: "3.7"
services:
  postgres:
    container_name: pg_ko_test_1
    image: postgres-ko:13.2
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOSTNAME: localhost
#      TZ: Asia/Seoul
    ports:
      - "15432:5432"
